### ISSUE TITLE
Notepad automatically opens

### ISSUE THREAD

**Issue by jonpalmisc** [jonpalmisc/bn-notepad#1]
Even though `False` is passed as the `default_visibility` parameter for the notepad widget upon registration, it automatically opens regardless, which is annoying.

https://github.com/jonpalmisc/bn-notepad/blob/6376b6634cb5c83e68c776f19e5333d92bcc4c1d/__init__.py#L7-L9

**Comment by SmoothHacker** [comment]
Doesn't happen to me.

**Comment by jonpalmisc** [comment]
Yeah, I went smooth-brain for a second. This isn't a real issue.
