### ISSUE TITLE
No warning to save when closing bndb after edits in notepad

### ISSUE THREAD

**Issue by galenbwill** [jonpalmisc/bn-notepad#3]
When edits in the notepad are the only changes in a bndb, there is no warning to save the bndb before closing it.

**Comment by jonpalmisc** [comment]
Great catch. I will look into how I can mark the BNDB as "dirty" if there are unsaved edits.

**Comment by jonpalmisc** [comment]
Should be fixed as of ebdfc9a82d9b9bbbfc10e8732c38a5a6d4f76bf7, available in release v0.3.1. I've tested this myself, but let me know if find any issues. If not, I'll close this.
