### ISSUE TITLE
Custom style sheets

### ISSUE THREAD

**Issue by galenbwill** [jonpalmisc/bn-notepad#6]
The [Markdown Preview Enhanced](https://github.com/shd101wyy/vscode-markdown-preview-enhanced) plugin for vscode supports customization through style sheets:

https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css

Not to the same degree, but something like it that would allow users to choose their own degree of desired formatting and things like proportional/mono fonts, font families and sizes, etc.

**Comment by jonpalmisc** [comment]
I think adding custom stylesheets would be a little excessive for this plugin. However, font configuration, etc. will be made available through settings.

**Comment by jonpalmisc** [comment]
Closing this in favor of #10 which is more in-line with the planned scope of the plugin.
